[package]
name = "s3-signer"
version = "0.0.5"
authors = [
  "Marc-Antoine Arnaud <maarnaud@media-io.com>",
]
edition = "2018"
readme = "README.md"
description = "A simple S3 signer in Rust"
repository = "https://github.com/media-io/s3-signer"
license = "MIT"

[dependencies]
async-h1 = "2.1.4"
async-std = { version = "1.7.0", features = ["attributes"] }
clap = "2.33"
http-types = "2.8.0"
log = "0.4"
rusoto_core = "0.46.0"
rusoto_credential = "0.46.0"
rusoto_signature = "0.46.0"
rusoto_s3 = "0.46.0"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
simple_logger = "1.11.0"
tokio = "1.5.0"

[build-dependencies]
built = "0.4"
